// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwQ4Ge0IXogltfcB5dj1pVkaRuShA7rBQ',
    appId: '1:878491995093:web:6ea2787f67957818648b5c',
    messagingSenderId: '878491995093',
    projectId: 'quicktask-31213',
    authDomain: 'quicktask-31213.firebaseapp.com',
    storageBucket: 'quicktask-31213.firebasestorage.app',
    measurementId: 'G-YRSM86YMG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5t2Z1qAXDOzjJoSPPe7E-dIOEfaIHr_I',
    appId: '1:878491995093:android:c16698cec50112fe648b5c',
    messagingSenderId: '878491995093',
    projectId: 'quicktask-31213',
    storageBucket: 'quicktask-31213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkwtlqyc820dZA6kRYh8whhyxNX1MIJ5E',
    appId: '1:878491995093:ios:0f817599a5c0359c648b5c',
    messagingSenderId: '878491995093',
    projectId: 'quicktask-31213',
    storageBucket: 'quicktask-31213.firebasestorage.app',
    androidClientId: '878491995093-h1ma0he5u8mljt1qbbah7olubh3cgk7r.apps.googleusercontent.com',
    iosClientId: '878491995093-phpo3nsargagofdsb8msokdm5hv601io.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkwtlqyc820dZA6kRYh8whhyxNX1MIJ5E',
    appId: '1:878491995093:ios:0f817599a5c0359c648b5c',
    messagingSenderId: '878491995093',
    projectId: 'quicktask-31213',
    storageBucket: 'quicktask-31213.firebasestorage.app',
    androidClientId: '878491995093-h1ma0he5u8mljt1qbbah7olubh3cgk7r.apps.googleusercontent.com',
    iosClientId: '878491995093-phpo3nsargagofdsb8msokdm5hv601io.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwQ4Ge0IXogltfcB5dj1pVkaRuShA7rBQ',
    appId: '1:878491995093:web:2bcd2b44344452a9648b5c',
    messagingSenderId: '878491995093',
    projectId: 'quicktask-31213',
    authDomain: 'quicktask-31213.firebaseapp.com',
    storageBucket: 'quicktask-31213.firebasestorage.app',
    measurementId: 'G-80PYVPPTWZ',
  );
}
